// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_net_entityframework.Data;

namespace WebAPI_net_entityframework.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20221004111026_T4")]
    partial class T4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI_net_entityframework.Data.ChiTietDHData", b =>
                {
                    b.Property<Guid>("MaDH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaHH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<double>("GiamGia")
                        .HasColumnType("float");

                    b.Property<int>("soluong")
                        .HasColumnType("int");

                    b.HasKey("MaDH", "MaHH");

                    b.HasIndex("MaHH");

                    b.ToTable("ChiTietDH");
                });

            modelBuilder.Entity("WebAPI_net_entityframework.Data.DonHangData", b =>
                {
                    b.Property<Guid>("MaDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiGiaoP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDH");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("WebAPI_net_entityframework.Data.HangHoaData", b =>
                {
                    b.Property<Guid>("MaHH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHH")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHH");

                    b.HasIndex("MaLoai");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("WebAPI_net_entityframework.Data.LoaiData", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("Loai");
                });

            modelBuilder.Entity("WebAPI_net_entityframework.Data.ChiTietDHData", b =>
                {
                    b.HasOne("WebAPI_net_entityframework.Data.DonHangData", "DonHang")
                        .WithMany("DHChiTiets")
                        .HasForeignKey("MaDH")
                        .HasConstraintName("FK_CHITIETDH_DONHANG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI_net_entityframework.Data.HangHoaData", "HangHoa")
                        .WithMany("DHChiTiets")
                        .HasForeignKey("MaHH")
                        .HasConstraintName("FK_CHITIETDH_HANGHOA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("WebAPI_net_entityframework.Data.HangHoaData", b =>
                {
                    b.HasOne("WebAPI_net_entityframework.Data.LoaiData", "Loai")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK_HANGHOA_LOAI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loai");
                });

            modelBuilder.Entity("WebAPI_net_entityframework.Data.DonHangData", b =>
                {
                    b.Navigation("DHChiTiets");
                });

            modelBuilder.Entity("WebAPI_net_entityframework.Data.HangHoaData", b =>
                {
                    b.Navigation("DHChiTiets");
                });

            modelBuilder.Entity("WebAPI_net_entityframework.Data.LoaiData", b =>
                {
                    b.Navigation("HangHoas");
                });
#pragma warning restore 612, 618
        }
    }
}
